name: Build uf2 files and create release

on:
  push:
    tags:
      - "v*"

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Set up TinyGo
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v0.27.0/tinygo_0.27.0_amd64.deb
        sudo dpkg -i tinygo_0.27.0_amd64.deb

    - name: Build and generate uf2 files for each script
      run: |
        tinygo build -target=xiao-rp2040 -o uncertainty-${{env.GITHUB_REF_NAME}}_burst.uf2 .\burst\
        tinygo build -target=xiao-rp2040 -o uncertainty-${{env.GITHUB_REF_NAME}}_lfo.uf2 .\lfo\
        tinygo build -target=xiao-rp2040 -o uncertainty-${{env.GITHUB_REF_NAME}}_vco.uf2 .\vco\
        tinygo build -target=xiao-rp2040 -o uncertainty-${{env.GITHUB_REF_NAME}}_voltage_gates.uf2 .\voltage_gates\

    - name: Create github release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: | 
          *.uf2
